config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }


  root 'home#index'
  get 'about', to: 'home#about'
  get 'contact', to: 'home#contact'
  post 'confirm', to: 'home#confirm'
  get 'chinhsach', to: 'home#privacy', as: 'privacy'
  get 'list_api', to: 'home#list_api', as: 'list_api'

  resources :musics

  resources :videos, only: [:index, :show]

  resources :messages
  resources :search, only: [:index]
  resources :articles, only: [:show, :edit, :update]
  resources :category_news, only: [:show]
  resources :category_video, only: [:show]
  resources :singer, only: [:index]
  get "singer/:id", to: "singer#show", constraints: { id: /[0-9]+/ }, as: "singer_show"

  resources :category_story, only: [:show] do
    resources :story_type, only: [:show]
  end

  resources :story_type, only: [:show] do
    resources :story, only: [:show]
  end

  resources :story, only: [:show] do
    resources :chapter, only: [:index, :show]
  end

  get "choose_chapter/:story_id/:id", to: "chapter#choose_chapter", as: "choose_chapter"

  ### redirect to root path if unknown root
  if Rails.env.production?
    get '*path' => redirect('/')
    get '404', :to => 'application#page_not_found'
    get '422', :to => 'application#server_error'
    get '500', :to => 'application#server_error'
  end

  namespace :admin do
    resources :home, only: [:index]
    get "ajax_sort_article", to: "home#sort_article"
  end

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/entities/story.rb
class Story < ActiveRecord::Base
  extend FriendlyId
  include Common
  friendly_id :name, use: :slugged
  before_save :remove_accent

  belongs_to :category_story
  has_many :chapters, dependent: :destroy

  validates :name, presence: true
end

app/models/entities/story_type.rb
class StoryType < ActiveRecord::Base
  extend FriendlyId
  include Common
  friendly_id :title, use: :slugged
  before_save :build_name_url

  belongs_to :category_story
  has_many :stories

  validates :title, presence: true

  def self.truyenchu
    find(54).stories.order(created_at: :desc).limit(10).sample(4)
  end
end

app/controllers/story_controller.rb
class StoryController < ApplicationController
  before_action :set_story

  def show
    @chapters = @story.chapters.page(params[:page])
  end

  private
  def set_story
    @story = Rails.cache.fetch("cache_set_story_show_#{params[:id]}") {
      Story.friendly.find(params[:id])
    }

    @story_type = Rails.cache.fetch("cache_set_story_type_show_#{@story.story_type_id}", expires_in: 90.hours) {
      StoryType.find(@story.story_type_id)
    }

    @category_story = Rails.cache.fetch("cache_category_story_default", expires_in: 90.hours) {
      CategoryStory.find(@story_type.category_story_id)
    }

    @recommend_stories = Rails.cache.fetch("cache_recommend_stories_in_chapter_#{@story.story_type_id}") {
      StoryType.find(@story.story_type_id).stories.order(updated_at: :desc).limit(10).sample(8)
    }
  end
end

app/views/story/show.html.erb
<%-
  @title_tag = "#{@story.try(:name)} - Siêu nhạc - sieunhac.com"
  @meta_description = "Dịch vụ chia sẻ #{@story.try(:name)} của sieu nhac, đến với trang web siêu nhạc, bạn sẽ tìm thấy tất cả các #{@story.try(:title)} đuợc nhiều nguời xem nhất hiện nay trên sieu nhac, đủ các thể loại, từ anime, commedy, 18+, adult, Đọc truyện tranh online mới nhất, sieunhac.com nhanh nhất như One Piece, Hiệp khách giang hồ, Fairy Tail, Naruto, Bleach,  sieunhac, Toriko..."
  @meta_robots = "index, follow"
  @meta_keywords = "sieunhac,#{@story.try(:name)}, Đọc truyện tranh online,One Piece, Hiệp khách giang hồ, Fairy Tail, sieunhac.com, Naruto, Bleach, Toriko"
  @meta_author = "Bản quyền của dịch vụ sieunhac.com."

  breadcrumb = []
  breadcrumb << { name: "Trang chủ", path: root_path }
  breadcrumb << { name: @category_story.try(:name), path: category_story_path(@category_story.id) }
  breadcrumb << { name: @story_type.title, path: story_type_path(@story_type.slug) }
  breadcrumb << { name: @story.name }
-%>

<%= render partial: "share/breadcrumb/breadcrumb",
    locals: { breadcrumb: breadcrumb, title: @story.try(:name) }
%>

<div class="container">
  <div class="row-fluid blog-page blog-item">
    <div class="span9">
      <div class="media">
        <a class="pull-left">
          <%= image_tag @story.image, class: "media-object"  %>
        </a>
        <div class="media-body">
          <h4 class="media-heading"><%= @story.name %></h4>
          <p><%= @story.short_content %></p>
          <hr />
          <!-- Nested media object -->
          <div class="span10">
            <table class="table table-bordered">
              <thead>
                <tr>
                  <th>Tên chương</th>
                  <th>Ngày cập nhật</th>
                </tr>
              </thead>
              <tbody>
                <% @chapters.each do |chapter| %>
                  <tr>
                    <td>
                      <%= link_to chapter.title, story_chapter_path(@story.slug, chapter.slug) %>
                    </td>
                    <td><%= chapter.updated_at %></td>
                  </tr>
                <% end %>
              </tbody>
            </table>
          </div>
        </div>
      </div><!--/media-->
    </div><!--/span9-->

    <!-- Right Sidebar -->
    <div class="span3">
      <div class="posts margin-bottom-20">
        <div class="headline"><h3>Truyện hot</h3></div>
        <% @recommend_stories.each do |recommend| %>
          <dl class="dl-horizontal">
            <dt>
              <%= link_to image_tag(recommend.image), story_path(recommend.slug) %>
            </dt>
            <dd>
              <p><%= link_to recommend.name, story_path(recommend.slug) %></p>
            </dd>
          </dl>
        <% end %>
      </div>
      <% cache("facebook_fanpage") do %>
        <%= render partial: "share/facebook/fanpage" %>
      <% end %>
    </div>
  </div>
  <div class="pagination pagination-centered">
    <%= paginate @chapters, :theme => 'twitter-bootstrap-3' %>
  </div>
</div>

app/views/story/show.js.erb
$("#results").append('<%= j render partial: "story/item", locals: {chapters: @chapters, story: @story} %>');
<% if @chapters.next_page %>
  $(".pagination").replaceWith('<%= j will_paginate @chapters %>');
<% else %>
  $(".pagination").remove();
<% end %>
<% sleep 1 %>