config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }


  root 'home#index'
  get 'about', to: 'home#about'
  get 'contact', to: 'home#contact'
  post 'confirm', to: 'home#confirm'
  get 'chinhsach', to: 'home#privacy', as: 'privacy'
  get 'list_api', to: 'home#list_api', as: 'list_api'

  resources :musics

  resources :videos, only: [:index, :show]

  resources :messages
  resources :search, only: [:index]
  resources :articles, only: [:show, :edit, :update]
  resources :category_news, only: [:show]
  resources :category_video, only: [:show]
  resources :singer, only: [:index]
  get "singer/:id", to: "singer#show", constraints: { id: /[0-9]+/ }, as: "singer_show"

  resources :category_story, only: [:show] do
    resources :story_type, only: [:show]
  end

  resources :story_type, only: [:show] do
    resources :story, only: [:show]
  end

  resources :story, only: [:show] do
    resources :chapter, only: [:index, :show]
  end

  get "choose_chapter/:story_id/:id", to: "chapter#choose_chapter", as: "choose_chapter"

  ### redirect to root path if unknown root
  if Rails.env.production?
    get '*path' => redirect('/')
    get '404', :to => 'application#page_not_found'
    get '422', :to => 'application#server_error'
    get '500', :to => 'application#server_error'
  end

  namespace :admin do
    resources :home, only: [:index]
    get "ajax_sort_article", to: "home#sort_article"
  end

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/controllers/admin/home_controller.rb
class Admin::HomeController < Admin::BaseController
  layout "admin"
  before_action :authenticate_admin

  def index
    if params["condition_sort"] == "Time"
      @articles = Article.all.order(id: :desc).page(params[:page])
    else
      @articles = Article.all.page(params[:page])
    end
    respond_to do |format|
      format.js
      format.html
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :set_default_music, only: [:contact]

  def index
    @unread_messages = nil
    @most_videos = Rails.cache.fetch("cache_youtube_top", expires_in: 6.hours) {
      Video.where(category_id: 12).order(updated_at: :desc).sample(4)
    }
    @saoviet = Rails.cache.fetch("cache_saoviet_top", expires_in: 2.hours) {
      CategoryNews.saoviet_top
    }
    @tamsu = Rails.cache.fetch("cache_tamsu_top", expires_in: 5.hours) {
      CategoryNews.tamsu
    }
    @doisong = Rails.cache.fetch("cache_doisong_top", expires_in: 4.hours) {
      CategoryNews.doisong
    }
    @truyenchu = Rails.cache.fetch("cache_truyenchu_top", expires_in: 64.hours) {
      StoryType.truyenchu
    }
    @bepeva = Rails.cache.fetch("cache_bepeva_top", expires_in: 6.hours) {
      CategoryNews.bepeva
    }
    @top_musics = Rails.cache.fetch("cache_musics_top", expires_in: 20.hours) { Music.top_musics_world }
  end

  def about; end

  def contact; end

  def privacy; end

  def list_api; end

  def confirm
    ContactMailer.send_contact(contact_params).deliver
    respond_to {|format| format.js}
  end

  private
  def contact_params
    params.permit(:name, :email, :content)
  end

  def set_default_music
    @music = Music.new
  end
end

app/views/home/about.html.erb
<div>
   <h1>This is page about</h1>
   <div ng-app="myApp1" ng-controller="nameCtrl">
     <ul>
       <li ng-repeat="x in names | orderBy : 'Country'">
       <td>{{x.Name}}</td>
       <td>{{x.Country}}</td>
       </li>
     </ul>
   </div>

</div>

app/views/home/confirm.js.erb
alert("Test");

app/views/home/contact.html.erb
<h1>This is contact form</h1>
<%= form_tag confirm_path, class: "form-horizontal", remote: true do %>
  <div class="form-group">
    <%= label_tag "Name", "Your name" %>
    <%= text_field_tag "name", nil, class: "form-control", placeholder: "Enter your name" %>
  </div>
  <div class="form-group">
    <%= label_tag "Email", "Your email" %>
    <%= text_field_tag "email", nil, class: "form-control", placeholder: "Enter your email" %>
  </div>
  <div class="form-group">
    <%= label_tag "Content", "Your content" %>
    <%= text_area_tag "content", nil, class: "form-control", placeholder: "Enter your content" %>
  </div>
  <div class="form-group">
    <%= submit_tag "Send", class: "btn btn-default", data: {confirm: "Are you sure ?"} %>
  </div>
<% end %>

app/views/home/index.html.erb
<%-
  @meta_robots = "index, follow"
  set_meta_tags og: {
    title:    'Trang chủ - sieunhac.com',
    type:     'Website',
    url:      "#{root_url}",
    image:    "#{image_url('sieunhac_v1.png')}",
    description: "Dịch vụ siêu nhạc với hàng trăm ngàn bài hát, truyện tranh, tiểu thuyết, showbiz,công nghệ,tin tức, sơn tùng mtp, sieunhac.com bạn có thể xem phim, xem video được cập nhật liên tục hàng giờ."
  }
-%>
<% title 'Siêu nhạc | Trang chủ - sieunhac.com' %>
<% description 'Dịch vụ siêu nhạc với hàng trăm ngàn bài hát, truyện tranh, tiểu thuyết, showbiz,công nghệ,tin tức, sơn tùng mtp, sieunhac.com bạn có thể xem phim, xem video được cập nhật liên tục hàng giờ.' %>
<% keywords 'nhac, truyen tranh, tin tuc, sieu nhac, video, son tung, mtp, sieunhac.com, showbiz' %>
<!-- Content Part -->
<div class="container">
  <!-- Service Blocks -->
  <%= render partial: "share/top/service_block_main", locals: { most_videos: @most_videos, title: "Danh sách video" } %>
  <!-- //End Service Blocks -->
  <%= render partial: "share/top/unify", locals: { title: "Sao việt", saoviet: @saoviet } %>
  <%= render partial: "share/top/unify", locals: { title: "Tâm sự", saoviet: @tamsu } %>
  <%= render partial: "share/top/unify", locals: { title: "Ẩm thực", saoviet: @bepeva } %>
  <%= render partial: "share/top/unify", locals: { title: "Đời sống", saoviet: @doisong } %>
  <%= render partial: "share/top/story", locals: { title: "Truyện tranh", truyen: @truyenchu } %>

  <!-- List these musics which hear most of times -->
  <%= render partial: "share/top/service/musics",
     locals: {
       title: "Bài hát nổi bật trong tuần",
       viet_music: @top_musics[0],
       us_music: @top_musics[1],
       lsx_music: @top_musics[2],
       traditional_music: @top_musics[3]} %>

  <!-- //End Accardion and Posts-->

</div><!--/container-->
<!-- End Content Part -->

app/views/home/list_api.html.erb
<%-
  breadcrumb = []
  breadcrumb << { name: "Trang chủ", path: root_path }
  breadcrumb << { name: "API" }
-%>
<%-
  @meta_robots = "index, follow"
  set_meta_tags og: {
    title:    "API-Sieunhac.com",
    type:     'Website',
    url:      privacy_path,
    description: "API-Sieunhac.com"
  }
-%>
<% title "API-Sieunhac.com" %>
<% description "API-Sieunhac.com" %>
<% keywords "API-Sieunhac.com" %>
<%= render partial: "share/breadcrumb/breadcrumb", locals: { breadcrumb: breadcrumb, title: "" } %>

<div class="container">
  <h1>We are updating API... <%= Time.zone.now %></h1>
  <h1>Please come back on next week</h1>
</div>

app/views/home/privacy.html.erb
<%-
  breadcrumb = []
  breadcrumb << { name: "Trang chủ", path: root_path }
  breadcrumb << { name: "Quy định sử dụng" }
-%>
<%-
  @meta_robots = "index, follow"
  set_meta_tags og: {
    title:    "Quy định sử dụng.",
    type:     'Website',
    url:      privacy_path,
    description: "Quy định sử dụng siêu nhạc."
  }
-%>
<% title "Quy định sử dụng." %>
<% description "Quy định sử dụng siêu nhạc." %>
<% keywords "Quy định sử dụng siêu nhạc, privacy" %>
<%= render partial: "share/breadcrumb/breadcrumb", locals: { breadcrumb: breadcrumb, title: "" } %>

<% cache("cache_page_privacy") do %>
  <div class="container">
    <div class="row-fluid privacy">
      <p class="lead" />
      <h1>Quy định pháp lý</h1>
      <p>Mời bạn vui lòng đọc kỹ các quy định sử dụng website dưới đây trước khi quyết định sử dụng thông tin, dịch vụ, sản phẩm của chúng tôi.</p><br />


      <h4>Trách nhiệm của chúng tôi đối với nội dung đăng tải</h4>
      <ul>
        <li>Các thông tin trên trang web này không phải đều hoàn chỉnh. Mặc dù chúng tôi đã cố gắng hết sức nhưng các thông tin trên trang web có thể không chính xác, chưa cập nhật hoặc không áp dụng đối với các trường hợp của một tình huống cụ thể.</li>

        <li>Mọi thông tin chung trên trang web này được cung cấp với thiện chí và xuất phát từ các nguồn thông tin được tin cậy là chính xác. Chúng tôi không chịu bất kỳ trách nhiệm nào đối với các thông tin chưa chính xác hoặc chưa hoàn chỉnh trên trang web (ngoại trừ các thông tin sai có tính gian lận) và bất kỳ quyết định nào của bạn dựa vào thông tin trên trang web này là trách nhiệm của riêng bạn. Chúng tôi không chịu trách nhiệm về bất kỳ tổn thất hoặc thiệt hại trực tiếp, gián tiếp, đặc biệt là kết quả hoặc tổn thất hoặc thiệt hại dưới hình thức khác phát sinh từ việc truy cập hoặc sử dụng trang web này hoặc bất kỳ thông tin nào trên trang web <%= link_to "sieunhac.com", root_url %>.</li>

        <li>Chúng tôi không bảo đảm rằng bất kỳ dữ liệu nào lấy từ trang web này không bị nhiễm virus hoặc bất kỳ lỗi hoặc khiếm khuyết nào. Trách nhiệm của bạn phải bảo đảm rằng bạn sử dụng phần mềm kiểm tra virus thích hợp. Tùy thuộc vào luật pháp mà không thể bị loại trừ, Chúng tôi không chịu trách nhiệm về bất kỳ tổn thất hoặc thiệt hại trực tiếp, gián tiếp, đặc biệt là kết quả của hoặc tổn thất hoặc thiệt hại dưới hình thức khác phát sinh từ việc truy cập hoặc sử dụng trang web này hoặc bất kỳ thông tin nào trên trang web.</li>

        <li>Mọi thông tin trên trang web <%= link_to "sieunhac.com", root_url %> chỉ mang tính cung cấp thông tin tham khảo và có thể chứa khiếm khuyết, chúng tôi luôn nỗ lực để khắc phục vấn đề này qua email liên hệ. Các tư vấn bệnh lý, sử dụng thuốc hay điều trị bệnh đều phải theo sự chỉ định của bác sĩ. Chúng tôi không chịu bất cứ trách nhiệm nào liên quan tới hậu quả hoặc thiệt hại do sử dụng thông tin từ chúng tôi.</li>
      </ul>

      <h4>Bản Quyền Tác Giả</h4>
      <ul>
        <li>Thông tin tại <%= link_to "sieunhac.com", root_url %> được chọn lọc từ các nguồn khác, bản quyền bài viết thuộc về tác giả nên chúng tôi không chấp nhận bất cứ trách nhiệm nào về các thông tin mà chúng tôi đăng tải, bạn sẽ sử dụng hoặc đặt niềm tin vào những thông tin đó với hiểu biết, trách nhiệm và nguy cơ của riêng bạn.</li>

        <li>Nếu bạn là Tác giả và Bản quyền của bài viết do <%= link_to "sieunhac.com", root_url %> sưu tầm được, xin vui lòng liên hệ với chúng tôi để được bổ sung thông tin về nội dung bài viết và tên tác giả cũng như điều kiện sử dụng.</li>
        <li>Nếu bạn cho rằng quyền sở hữu của bạn đã bị sử dụng theo những cách thức vi phạm quyền tác giả, bạn có thể liên hệ với chúng tôi tại địa chỉ: sieunhac1990@gmail.com</li>
      </ul>

      <h4>Luật Pháp Nào Điều Chỉnh Trang Web Này?</h4>
      <ul>
        <li>Trong trường hợp bất kỳ hoặc phần nào của điều khoản trong các điều khoản và điều kiện tuyên bố là vô hiệu, trái pháp luật hoặc không có hiệu lực thi hành trong phạm vi nào đó theo quyết định của cơ quan nhà nước có thẩm quyền, điều khoản trong phạm vi đó sẽ được tách ra khỏi các điều khoản còn lại và các điều khoản còn lại vẫn tiếp tục có hiệu lực và giá trị thi hành trong phạm vi đầy đủ nhất theo quy định của luật pháp.</li>
      </ul>

      <h4>Thay đổi quy định</h4>
      <ul>
        <li>Chúng tôi có toàn quyền thay đổi quy định mà không cần báo trước. Với việc tiếp tục sử dụng sieunhac.com sau những sửa đổi đó, bạn mặc nhiên đồng ý chấp hành các sửa đổi trong quy định.</li>
      </ul>

      <h4>Luật áp dụng</h4>
      <ul>
        <li>Bạn đồng ý rằng bản Quy định sử dụng và bất kỳ bất đồng nào phát sinh từ việc bạn sử dụng website này hoặc các sản phẩm và dịch vụ của chúng tôi sẽ được giải quyết theo luật pháp hiện hành của Nước Cộng hoà Xã hội Chủ nghĩa Việt Nam. Thông qua việc đăng ký hoặc sử dụng website và dịch vụ của chúng tôi, bạn mặc nhiên đồng ý và tuân thủ toàn bộ các quy định của Luật pháp Việt Nam.</li>
        <li class="css_privacy">Lưu ý: Các điều kiện này có thể được sửa đổi, bổ sung bất cứ lúc nào mà không cần phải báo trước và có hiệu lực ngay khi được thay đổi.
        Vui lòng liên hệ chúng tôi nếu bạn có bất kỳ thắc mắc!</li>
      </ul>
    </div><!--/row-fluid-->
  </div><!--/container-->
  <!--=== End Content Part ===-->
<% end %>