config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }


  root 'home#index'
  get 'about', to: 'home#about'
  get 'contact', to: 'home#contact'
  post 'confirm', to: 'home#confirm'
  get 'chinhsach', to: 'home#privacy', as: 'privacy'
  get 'list_api', to: 'home#list_api', as: 'list_api'

  resources :musics

  resources :videos, only: [:index, :show]

  resources :messages
  resources :search, only: [:index]
  resources :articles, only: [:show, :edit, :update]
  resources :category_news, only: [:show]
  resources :category_video, only: [:show]
  resources :singer, only: [:index]
  get "singer/:id", to: "singer#show", constraints: { id: /[0-9]+/ }, as: "singer_show"

  resources :category_story, only: [:show] do
    resources :story_type, only: [:show]
  end

  resources :story_type, only: [:show] do
    resources :story, only: [:show]
  end

  resources :story, only: [:show] do
    resources :chapter, only: [:index, :show]
  end

  get "choose_chapter/:story_id/:id", to: "chapter#choose_chapter", as: "choose_chapter"

  ### redirect to root path if unknown root
  if Rails.env.production?
    get '*path' => redirect('/')
    get '404', :to => 'application#page_not_found'
    get '422', :to => 'application#server_error'
    get '500', :to => 'application#server_error'
  end

  namespace :admin do
    resources :home, only: [:index]
    get "ajax_sort_article", to: "home#sort_article"
  end

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/entities/story.rb
class Story < ActiveRecord::Base
  extend FriendlyId
  include Common
  friendly_id :name, use: :slugged
  before_save :remove_accent

  belongs_to :category_story
  has_many :chapters, dependent: :destroy

  validates :name, presence: true
end

app/models/entities/story_type.rb
class StoryType < ActiveRecord::Base
  extend FriendlyId
  include Common
  friendly_id :title, use: :slugged
  before_save :build_name_url

  belongs_to :category_story
  has_many :stories

  validates :title, presence: true

  def self.truyenchu
    find(54).stories.order(created_at: :desc).limit(10).sample(4)
  end
end

app/controllers/story_controller.rb
class StoryController < ApplicationController
  before_action :set_story

  def show
    @chapters = @story.chapters.page(params[:page])
  end

  private
  def set_story
    @story = Rails.cache.fetch("cache_set_story_show_#{params[:id]}") {
      Story.friendly.find(params[:id])
    }

    @story_type = Rails.cache.fetch("cache_set_story_type_show_#{@story.story_type_id}", expires_in: 90.hours) {
      StoryType.find(@story.story_type_id)
    }

    @category_story = Rails.cache.fetch("cache_category_story_default", expires_in: 90.hours) {
      CategoryStory.find(@story_type.category_story_id)
    }

    @recommend_stories = Rails.cache.fetch("cache_recommend_stories_in_chapter_#{@story.story_type_id}") {
      StoryType.find(@story.story_type_id).stories.order(updated_at: :desc).limit(10).sample(8)
    }
  end
end

app/views/share/story/_chapter_picture.html.erb
<% chapter.image.split(",").each do |item| %>
  <div class="blog-img">
    <img class="lazy" data-src="<%= item %>" src="http://sieunhac.com/images/download.gif" border="0" alt="" />
  </div>
<% end %>

app/views/share/story/_story_item.html.erb
<% stories.each_slice(2) do |story| %>
  <div class="row-fluid">
    <% story.each do |item|%>
      <div class="span6 booking-blocks">
        <div class="pull-left booking-img">
          <% if item.image.present? %>
            <%= link_to image_tag(item.image, class: "css_image_search"), story_path(item.slug), target: "_blank", rel: "follow" %>
          <% else %>
            <%= link_to image_tag("/images/stories/story_2.jpg", class: "css_image_search"), story_path(item.slug), target: "_blank", rel: "follow" %>
          <% end %>
          <ul class="unstyled">
            <li><i class="icon-time"></i><%= format_date_time(item.created_at) %></li>
          </ul>
        </div>
        <div style="overflow:hidden;">
          <h2 class="article_title">
            <%= link_to item.name, story_path(item.slug), class: "css_decorate_link_none_article", target: "_blank", rel: "follow" %>
          </h2>
          <%= short_content_article(item.short_content) %>
        </div>
      </div>
    <% end %>
  </div>
<% end %>

app/views/share/story/_story_type.html.erb
<div class="row-fluid margin-bottom-20">
  <!-- Unordered Lists -->
  <% divide_type = (story_types.size / 4.0).ceil %>
  <% story_types.each_slice(divide_type) do |types| %>
    <div class="span3">
      <ul>
        <% types.each do |type| %>
          <li><%= link_to type.title, story_type_path(type.slug) , target: "_blank", rel: "follow"%></li>
        <% end %>
      </ul>
    </div>
  <% end %>
</div><!--/row-fluid-->