config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }


  root 'home#index'
  get 'about', to: 'home#about'
  get 'contact', to: 'home#contact'
  post 'confirm', to: 'home#confirm'
  get 'chinhsach', to: 'home#privacy', as: 'privacy'
  get 'list_api', to: 'home#list_api', as: 'list_api'

  resources :musics

  resources :videos, only: [:index, :show]

  resources :messages
  resources :search, only: [:index]
  resources :articles, only: [:show, :edit, :update]
  resources :category_news, only: [:show]
  resources :category_video, only: [:show]
  resources :singer, only: [:index]
  get "singer/:id", to: "singer#show", constraints: { id: /[0-9]+/ }, as: "singer_show"

  resources :category_story, only: [:show] do
    resources :story_type, only: [:show]
  end

  resources :story_type, only: [:show] do
    resources :story, only: [:show]
  end

  resources :story, only: [:show] do
    resources :chapter, only: [:index, :show]
  end

  get "choose_chapter/:story_id/:id", to: "chapter#choose_chapter", as: "choose_chapter"

  ### redirect to root path if unknown root
  if Rails.env.production?
    get '*path' => redirect('/')
    get '404', :to => 'application#page_not_found'
    get '422', :to => 'application#server_error'
    get '500', :to => 'application#server_error'
  end

  namespace :admin do
    resources :home, only: [:index]
    get "ajax_sort_article", to: "home#sort_article"
  end

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/entities/music.rb
class Music < ActiveRecord::Base
  paginates_per 10

  mount_uploader :image, MusicUploader
  belongs_to :category
  belongs_to :singer

  validates :title,
    presence: { message: "Không đuợc để trống" },
    length: { maximum: 100 }

  validates :type_music,
    presence: { message: "Không đuợc để trống" },
    length: { maximum: 100 }

  validates :format,
    presence: { message: "Không đuợc để trống" },
    length: { maximum: 100 }

  validates :singer_name,
    presence: { message: "Không đuợc để trống" },
    length: { maximum: 100 }

  validates :url_original,
    presence: { message: "Không đuợc để trống" },
    length: { minimum: 10 }

  validates :site_id,
    presence: { message: "Không đuợc để trống" },
    length: { minimum: 1 }

  def search(params)
    Search.new(queries: execute_query(params), pg: params[:page], start: nil, sort: "updated_at").paginater
  end

  def self.detail(id)
    Search.new(queries: "id: #{id}", pg: nil, start: nil, sort: "updated_at").detail
  end

  def self.lansongxanh
    Search.new(queries: "site_id: 2", pg: nil, start: nil, sort: "updated_at").detail
  end

  def self.recommend(music)
    Search.new(queries: "singer_name: #{music['singer_name']}", pg: nil, start: nil, sort: "updated_at").detail
  end

  def self.singer_detail(id, page)
    Search.new(queries: "singer_id: #{id}", pg: page, start: nil, sort: "updated_at").paginater
  end

  def self.top_musics_world
    [
      Search.new(queries: "nhachot: true", pg: nil, start: nil, sort: "updated_at").detail,
      Search.new(queries: "music_top: true", pg: nil, start: nil, sort: "updated_at").detail,
      Search.new(queries: "lsxanh: true", pg: nil, start: nil, sort: "updated_at").detail,
      Search.new(queries: "site_id: 5", pg: nil, start: nil, sort: "updated_at").detail
    ]
  end

  private
  def filter_query(query)
    query.gsub(/[\#|\!|\@|\%|\^|\$|\~|\`|\&|\*|\(|\)|\-|\_|\=|\+|\]|\[|\{|\}|\"|\'|\;|\:|\?|\/|\>|\.|\<|\,|\||\\]/, "")
  end

  def execute_query(params)
    query = filter_query(params[:query]).try(:to_s).try(:strip).try(:squish) if params[:query].try(:strip).try(:squish).present?
    query.present? ? build_query(query) : "*:*"
  end

  def build_query(query)
    "title:(#{query}) OR singer_name:(#{query})"
  end

end

app/controllers/musics_controller.rb
class MusicsController < ApplicationController
  before_action :set_music, only: [:edit, :update, :destroy]

  def index
    @musics = Music.page(params[:page])
  end

  def edit; end

  def show
    @music = Rails.cache.fetch("cache_music_controller_show_#{params[:id]}", expires_in: 80.hours) do
      Music.detail(params[:id]).first
    end

    @music_recommend = Rails.cache.fetch("cache_music_controller_show_recommend_#{params[:id]}", expires_in: 3.hours) do
      Music.recommend(@music).sample(6)
    end
  end

  def new
    @music = Music.new
  end

  def create
    @music = Music.new(music_params)
    if @music.save
      redirect_to musics_path, notice: "Create a new music successfull"
    else
      render :new
    end
  end

  def update
    if @music.update(music_params)
    else
      render :edit
    end
  end

  def destroy
    @music.destroy
  end

  private
  def set_music
    @music = Music.find_by(params[:id])
  end

  def music_params(music_params=:music)
    params.require(music_params).permit(
      :title,
      :type_music,
      :format,
      :album,
      :singer,
      :lyrics,
      :country,
      :url,
      :url_original,
      :birthday_singer,
      :information,
      :quantity,
      :artist,
      :image,
      :category_id
    )
  end

  def rebuild_params
    music_params[:birthday_singer] = DateTime.strptime(music_params["birthday_singer"], '%m/%d/%Y')
  end
end

app/views/musics/index.html.erb
<div>
  <div>
    <%= link_to "Create new", new_music_path %>
  </div>
  <h1>This is page list all musics</h1>
  <div>
    <% @musics.each do |music| %>
      <%= music.title %>
      <%= music.type_music %>
    <% end %>
  </div>
</div>
<%= paginate @musics %>

app/views/musics/new.html.erb
<div>
  <h1>Create new music</h1>
  <%= render partial: "musics/form/form", locals: { music: @music } %>
</div>

app/views/musics/show.html.erb
<%-
  @title_tag = "#{song_title(@music["title"], false)}-#{@music["singer"]} | Bài hát, mp3, lyrics"
  @meta_title = "#{song_title(@music["title"], false)}-#{@music["singer"]} | Bài hát, mp3, lyrics - Siêu nhạc - sieunhac.com"
  @meta_description = "sieunhac.com #{song_title(@music["title"], false)}, #{@music["singer"]}. #{song_lyrics(@music["lyrics"], true)}. Tải download 320 nhạc chờ từ siêu nhạc #{song_title(@music["title"], false)},#{@music["singer"]}"
  @meta_robots = "index, follow"
  @meta_keywords = "#{song_title(@music["title"], false)}, #{@music["singer"]}, , , loi bai hat, tai nhac 320, lossless, nhac cho"
  @meta_author = "Bản quyền của dịch vụ sieu nhac."
  breadcrumb = []
  breadcrumb << { name: "Trang chủ", path: root_path }
  breadcrumb << { name: @music["singer_name"], path: singer_show_path(@music["singer_id"].to_i)}
  breadcrumb << { name: song_title(@music["title"], false) }
-%>

<%= render partial: "share/breadcrumb/breadcrumb", locals: { breadcrumb: breadcrumb, title: "Bài hát" } %>
<!--=== Content Part ===-->
<div class="container">
  <div class="row-fluid blog-page blog-item">
    <!-- Left Sidebar -->
    <div class="span9">
      <div class="blog margin-bottom-30">
        <h3><%= song_title(@music["title"], false) %></h3>
        <ul class="unstyled inline blog-info">
          <li><i class="icon-calendar"></i> <%= @music["updated_at"] %></li>
          <li><i class="icon-pencil"></i> <%= song_singer(@music["singer_name"], false) %></li>
        </ul>
        <ul class="unstyled inline blog-tags">
          <li>
            <i class="icon-tags"></i>
            <%= link_to @music["type_music"], "" %>
            <%= link_to @music["country"], "" %>
          </li>
        </ul>
        <div class="blog-img">
          <%= render partial: "share/media", locals: { music: @music } %>
        </div>
        <%= render partial: "share/facebook/share", locals: { url: music_url(@music["id"])} %>
        <blockquote class="hero">
          <p><%= song_lyrics(@music["lyrics"], false) %></p>
        </blockquote>
      </div><!--/blog-->
      <hr />

      <!-- Media -->
      <div class="media">
        <div class="fb-comments" data-href="<%= music_url(@music["id"].to_i) %>" data-width="869.984" data-numposts="5"></div>
      </div><!--/media-->
    </div><!--/span9-->

    <!-- Right Sidebar -->
    <div class="span3">
      <!-- Blog Tags -->
      <div class="headline"><h3>Blog Tags</h3></div>
      <ul class="unstyled inline blog-tags">
        <li><a href="#"><i class="icon-tags"></i> Business</a></li>
      </ul>

      <!-- Blog Latest Tweets -->
      <div class="blog-twitter">
        <div class="headline"><h3>Bài hát liên quan</h3></div>
        <% @music_recommend.each do |recommend| %>
          <p>
            <li><i class="icon-user-md"></i><%= song_title(recommend["title"], false) %></li>
            <% if recommend["singer_image"].present? %>
              <%= link_to image_tag(recommend["singer_image"], class: "css_video_recommend", title: recommend["title"]), music_path(recommend["id"].to_i), target: "_blank", rel: "follow" %>
            <% else %>
              <%= link_to image_tag("/images/musics/default.jpg", class: "css_video_recommend", title: recommend["title"]), music_path(recommend["id"].to_i), target: "_blank", rel: "follow" %>
            <% end %>
          </p>
        <% end %>
      </div>
    </div><!--/span3-->
  </div><!--/row-fluid-->
</div><!--/container-->

<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
<script type="text/javascript">
  $(function() {
    $('.slider4').bxSlider({
      slideWidth: 200,
      minSlides: 2,
      maxSlides: 5,
      moveSlides: 1,
      captions: true,
      slideMargin: 10
    });
  });
</script>